'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { Trash2, Info } from 'lucide-react';
import api from '@/lib/axios';
import { toast } from '@/hooks/useToast';
import { Card } from '@/components/ui/Card';
import { LoadingSkeleton } from '@/components/ui/LoadingSkeleton';
import { Modal } from '@/components/ui/Modal';
import type { Scenario, Forecast, TrainedModel } from '@/types';
import { formatDate } from '@/lib/utils';

/**
 * Scenario list page. A base forecast from the active model is required so the
 * side-by-side charts have real data to display.
 */
export default function ScenariosPage() {
  const queryClient = useQueryClient();
  const [showModal, setShowModal] = useState(false);
  const [name, setName] = useState('');
  const [baseForecastId, setBaseForecastId] = useState('');
  const [notes, setNotes] = useState('');

  const { data: scenarios = [], isLoading } = useQuery<Scenario[]>({
    queryKey: ['scenarios'],
    queryFn: () => api.get('/api/scenarios').then((r) => r.data?.data ?? r.data ?? []),
  });

  const { data: forecasts = [] } = useQuery<Forecast[]>({
    queryKey: ['forecasts'],
    queryFn: () => api.get('/api/forecasts').then((r) => r.data?.data ?? r.data ?? []),
  });

  const { data: models = [] } = useQuery<TrainedModel[]>({
    queryKey: ['models'],
    queryFn: () => api.get('/api/models').then((r) => r.data?.data ?? r.data ?? []),
  });

  const activeModel = models.find((m) => m.active);

  // Sort: active-model forecasts first, then the rest
  const sortedForecasts = [...forecasts].sort((a, b) => {
    const aActive = activeModel && a.modelId === activeModel.id ? 0 : 1;
    const bActive = activeModel && b.modelId === activeModel.id ? 0 : 1;
    return aActive - bActive;
  });

  const createMutation = useMutation({
    mutationFn: (payload: { name: string; baseForecastId: string; notes: string }) =>
      api.post('/api/scenarios', payload).then((r) => r.data?.data ?? r.data),
    onSuccess: (scenario: { name: string }) => {
      queryClient.invalidateQueries({ queryKey: ['scenarios'] });
      toast.success('Scenario created', `"${scenario.name}" is ready for analysis.`);
      setShowModal(false);
      setName('');
      setBaseForecastId('');
      setNotes('');
    },
    onError: (err: unknown) => {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message;
      toast.error('Failed to create scenario', msg ?? 'Please check your inputs and try again.');
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => api.delete(`/api/scenarios/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['scenarios'] });
      toast.success('Scenario deleted');
    },
    onError: () => toast.error('Delete failed', 'Could not delete the scenario.'),
  });

  const canSubmit = name.trim().length > 0 && baseForecastId !== '' && !createMutation.isPending;

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Scenario Analysis</h1>
          <p className="text-sm text-gray-500 mt-1">Build what-if scenarios against forecast data</p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="px-4 py-2 bg-brand text-white rounded-lg text-sm hover:bg-brand-light"
        >
          + New Scenario
        </button>
      </div>

      {/* Info banner */}
      <div className="flex items-start gap-3 p-4 bg-blue-50 border border-blue-200 rounded-xl text-sm text-blue-800">
        <Info className="w-4 h-4 mt-0.5 flex-shrink-0 text-blue-500" />
        <div>
          <p className="font-medium">Scenarios require a base forecast</p>
          <p className="text-blue-700 text-xs mt-0.5">
            Each scenario is built on top of a forecast generated by a trained model. Without a base forecast
            the side-by-side charts will be empty. Use a forecast from the{' '}
            <strong>active model</strong> for the most up-to-date projections.
          </p>
        </div>
      </div>

      <Card>
        {isLoading ? (
          <div className="p-6 space-y-3">
            {[1, 2, 3].map((i) => <LoadingSkeleton key={i} className="h-10 w-full" />)}
          </div>
        ) : scenarios.length === 0 ? (
          <div className="p-12 text-center text-gray-500">
            <p className="text-lg font-medium">No scenarios yet</p>
            <p className="text-sm mt-1">Create a scenario to explore what-if analysis.</p>
          </div>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                {['Name', 'Flagged', 'Created At', ''].map((h) => (
                  <th key={h} className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {scenarios.map((s) => (
                <tr key={s.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 font-medium text-gray-800">{s.name}</td>
                  <td className="px-4 py-3">
                    {s.flaggedForReview ? (
                      <span className="text-amber-500 text-base" title="Flagged for executive review">🚩</span>
                    ) : (
                      <span className="text-gray-300">-</span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-gray-500">{formatDate(s.createdAt)}</td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex items-center justify-end gap-3">
                      <Link href={`/decisions/scenarios/${s.id}`} className="text-brand hover:underline text-xs font-medium">
                        Open →
                      </Link>
                      <button
                        onClick={() => {
                          if (confirm(`Delete scenario "${s.name}"? This cannot be undone.`)) {
                            deleteMutation.mutate(s.id);
                          }
                        }}
                        disabled={deleteMutation.isPending}
                        className="text-gray-400 hover:text-red-600 disabled:opacity-40 transition-colors"
                        title="Delete scenario"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Card>

      <Modal isOpen={showModal} onClose={() => setShowModal(false)} title="New Scenario">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Scenario Name</label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
              placeholder="e.g. High demand Q3 2027"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Base Forecast <span className="text-red-500">*</span>
            </label>
            <select
              value={baseForecastId}
              onChange={(e) => setBaseForecastId(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm"
            >
              <option value="">Select a forecast…</option>
              {sortedForecasts.map((f) => {
                const isActive = activeModel && f.modelId === activeModel.id;
                return (
                  <option key={f.id} value={f.id}>
                    {isActive ? '★ ' : ''}{f.modelName ?? 'Unknown model'} - {f.horizonMonths}-month forecast
                    {isActive ? ' (active model)' : ''}
                  </option>
                );
              })}
            </select>
            {forecasts.length === 0 && (
              <p className="text-xs text-amber-600 mt-1">
                No forecasts available. Generate a forecast first from the Forecasts page.
              </p>
            )}
            {forecasts.length > 0 && (
              <p className="text-xs text-gray-500 mt-1">
                Forecasts marked with ★ are from the active model and give the most reliable baseline.
              </p>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm resize-none"
              placeholder="Optional strategic notes…"
            />
          </div>

          <button
            disabled={!canSubmit}
            onClick={() => createMutation.mutate({ name, baseForecastId, notes })}
            className="w-full bg-brand text-white py-2 rounded-lg text-sm hover:bg-brand-light disabled:opacity-50"
          >
            {createMutation.isPending ? 'Creating…' : 'Create Scenario'}
          </button>
        </div>
      </Modal>
    </div>
  );
}
